
name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env: 
        CLONE_DIR: /home/john/node-grp6/
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: CLONE_DIR
        script: |
          echo 'Coucou La team Simplon Prod :D'
          mkdir -p /home/john/node-grp6/
          mkdir -p /home/john/node-grp6-temp/
          git clone -b develop git@github.com:marouatnk/deploy_api.git /home/john/node-grp6-temp/
          cd /home/john/node-grp6-temp/
          npm install
          npm run build
          cp .env.beta ./dist/.env
          cd dist
          npm install --production
          sed -i 's/xport/${{ secrets.EXPRESS_PORT }}/g' .env
          rm -rf /home/john/node-grp6/*
          cp -r /home/john/node-grp6-temp/dist /home/john/node-grp6/dist
          rm -rf /home/john/node-grp6-temp
          cd /home/john/node-grp6/dist
          pm2 start index.js --name "app-grp6"
